### ISSUE TITLE
Modify `Ǔ`'s vectorisation

### ISSUE THREAD

**Issue by chunkybanana** [Vyxal/Vyxal#205] opened 2021-07-29 07:49 UTC
`vǓ` should rotate each item of said list left by one, or more if there is a number before that on the stack. Instead... Well, try [this](https://lyxal.pythonanywhere.com?flags=&code=%5Ca%20%60hello%60%3A%22v%C7%93&inputs=&header=&footer=). The `\a` is there to stop Vyxal from popping a 0 to rotate by, but in theory should have no affect. In practice...

**Comment by Lyxal** [comment] 2021-08-31 06:47
This actually isn't a bug, but rather intended behaviour

**Comment by Lyxal** [comment] 2021-08-31 06:47
Vectorisation works off arity, and `Ǔ` is defined to have an arity of 2, meaning it always pops 2 items no matter what the type patterns are

**Comment by Lyxal** [comment] 2021-08-31 06:49
The only bug here is that it takes its arguments in reverse for some reason, which is easily fixed in the rewrite

**Comment by Lyxal** [comment] 2021-08-31 06:49
and then that mightn't be vectorisation; the problem could lie within the elements file

**Comment by Lyxal** [comment] 2021-12-20 05:18
This is fixed and should be closed.

**Closed by Lyxal** 2021-12-20 05:18 UTC
Labels: enhancement, difficulty: easy, priority:medium
